### ISSUE TITLE
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GrantHov** [Gabaldonlab/crossmapper#5]
when installing with conda 4.11.0 with commands

```
conda create -n py36 python=3.6
source activate py36
conda install -c gabaldonlab -c bioconda crossmapper=1.1.1

```
crossmapper -h produces the following error:

```
Traceback (most recent call last):
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/bin/crossmapper", line 11, in <module>
    load_entry_point('crossmapper==1.1.1', 'console_scripts', 'crossmapper')()
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2872, in load_entry_point
    return ep.load()
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/site-packages/crossmapper/__init__.py", line 3, in <module>
    from .crossmapper import crossmapMain
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/site-packages/crossmapper/crossmapper.py", line 14, in <module>
    from crossmapper.countUtil import getReadCounters
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/site-packages/crossmapper/countUtil.py", line 1, in <module>
    import pysam
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/site-packages/pysam/__init__.py", line 16, in <module>
    import pysam.libcsamfile as libcsamfile
  File "pysam/libcsamfile.pyx", line 1, in init pysam.libcsamfile
  File "pysam/libcalignedsegment.pyx", line 60, in init pysam.libcalignedsegment
  File "/gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/py36/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

Env details : 

```

conda list --explicit

 This file may be used to create an environment using:

 $ conda create --name <env> --file <this file>

 platform: linux-64

@EXPLICIT

https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.36.1-hea4e1c9_2.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2021.10.8-ha878542_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libgfortran5-11.2.0-h5c6108e_11.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-11.2.0-he4da1e4_11.tar.bz2

https://conda.anaconda.org/bioconda/linux-64/star-2.7.9a-h9ee0642_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libgfortran-ng-11.2.0-h69a702a_11.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libgomp-11.2.0-h1d223b6_11.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_gnu.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-11.2.0-h1d223b6_11.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h7f98852_4.tar.bz2

https://conda.anaconda.org/bioconda/linux-64/libdeflate-1.0-h14c3975_1.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libffi-3.4.2-h7f98852_5.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libopenblas-0.3.18-pthreads_h8fe5266_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libzlib-1.2.11-h36c2ea0_1013.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.1-hf484d3e_1002.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1l-h7f98852_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/perl-5.32.1-1_h7f98852_perl5.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.5-h516909a_1.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/yaml-0.2.5-h516909a_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libblas-3.9.0-12_linux64_openblas.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libedit-3.1.20191231-h46ee950_2.tar.bz2

```

```
$conda env export

name: env_crossmapper

channels:

  - gabaldonlab

  - bioconda

  - conda-forge

  - defaults

  - r

  - anaconda

dependencies:

  - _libgcc_mutex=0.1=conda_forge

  - _openmp_mutex=4.5=1_gnu

  - biopython=1.79=py36h8f6f2f9_0

  - bwa=0.7.17=h5bf99c6_8

  - bzip2=1.0.8=h7f98852_4

  - ca-certificates=2021.10.8=ha878542_0

  - certifi=2021.5.30=py36h5fab9bb_0

  - crossmapper=1.1.1=py36_1

  - curl=7.71.1=he644dc0_3

  - gffread=0.12.7=h9a82719_0

  - jinja2=3.0.3=pyhd8ed1ab_0

  - krb5=1.17.2=h926e7f8_0

  - ld_impl_linux-64=2.36.1=hea4e1c9_2

  - libblas=3.9.0=12_linux64_openblas

  - libcblas=3.9.0=12_linux64_openblas

  - libcurl=7.71.1=hcdd3856_3

  - libdeflate=1.0=h14c3975_1

  - libedit=3.1.20191231=h46ee950_2

  - libffi=3.4.2=h7f98852_5

  - libgcc-ng=11.2.0=h1d223b6_11

  - libgfortran-ng=11.2.0=h69a702a_11

  - libgfortran5=11.2.0=h5c6108e_11

  - libgomp=11.2.0=h1d223b6_11

  - liblapack=3.9.0=12_linux64_openblas

  - libopenblas=0.3.18=pthreads_h8fe5266_0

  - libssh2=1.10.0=ha56f1ee_2

  - libstdcxx-ng=11.2.0=he4da1e4_11

  - libzlib=1.2.11=h36c2ea0_1013

  - markupsafe=2.0.1=py36h8f6f2f9_0

  - ncurses=6.1=hf484d3e_1002

  - numpy=1.19.5=py36hfc0c790_2

  - openssl=1.1.1l=h7f98852_0

  - perl=5.32.1=1_h7f98852_perl5

  - pigz=2.6=h27826a3_0

  - pip=21.3.1=pyhd8ed1ab_0

  - pysam=0.15.3=py36hda2845c_1

  - python=3.6.8=h0371630_0

  - python_abi=3.6=2_cp36m

  - pyyaml=5.4.1=py36h8f6f2f9_1

  - readline=7.0=hf8c457e_1001

  - samtools=1.9=h8571acd_11

  - setuptools=49.6.0=py36h5fab9bb_3

  - sqlite=3.28.0=h8b20d00_0

  - star=2.7.9a=h9ee0642_0

  - tk=8.6.11=h27826a3_1

  - wgsim=1.0=h5bf99c6_4

  - wheel=0.37.0=pyhd8ed1ab_1

  - xz=5.2.5=h516909a_1

  - yaml=0.2.5=h516909a_0

  - zlib=1.2.11=h36c2ea0_1013

prefix: /gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/env_crossmapper
```

**Comment by ahmedihafez** [comment]
Hi @GrantHov , I am trying to reproduce this but I am not sure which version of OpenSuse have this issue, I tried it with opensuse-leap-15.1m but I ended having different env.
However The problem could be with python version that is required with some of the dependency.
Can you try to install python version 3.6.10 using the next command
```
conda install python=3.6.10
``` 
this should change ```libffi``` to a correct working version.
Try it then share the env here to look into it.

**Comment by GrantHov** [comment]
OpenSure is Leap 15.0

tried with new python version, and got the same error:



@EXPLICIT

https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2021.10.8-ha878542_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.36.1-hea4e1c9_2.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libgfortran5-11.2.0-h5c6108e_11.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-11.2.0-he4da1e4_11.tar.bz2

https://conda.anaconda.org/bioconda/linux-64/star-2.7.9a-h9ee0642_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libgfortran-ng-11.2.0-h69a702a_11.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libgomp-11.2.0-h1d223b6_11.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_gnu.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-11.2.0-h1d223b6_11.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h7f98852_4.tar.bz2

https://conda.anaconda.org/bioconda/linux-64/libdeflate-1.0-h14c3975_1.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libffi-3.3-h58526e2_2.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libopenblas-0.3.18-pthreads_h8fe5266_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libzlib-1.2.11-h36c2ea0_1013.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.1-hf484d3e_1002.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1l-h7f98852_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/perl-5.32.1-1_h7f98852_perl5.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.5-h516909a_1.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/yaml-0.2.5-h516909a_0.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libblas-3.9.0-12_linux64_openblas.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/libedit-3.1.20191231-h46ee950_2.tar.bz2

https://conda.anaconda.org/conda-forge/linux-64/readline-7.0-hf8c457e_1001.tar.bz2



name: env_crossmapper

channels:

  - gabaldonlab

  - bioconda

  - conda-forge

  - defaults

  - r

  - anaconda

dependencies:

  - _libgcc_mutex=0.1=conda_forge

  - _openmp_mutex=4.5=1_gnu

  - biopython=1.79=py36h8f6f2f9_0

  - bwa=0.7.17=h5bf99c6_8

  - bzip2=1.0.8=h7f98852_4

  - ca-certificates=2021.10.8=ha878542_0

  - certifi=2021.5.30=py36h5fab9bb_0

  - crossmapper=1.1.1=py36_1

  - curl=7.71.1=he644dc0_3

  - gffread=0.12.7=h9a82719_0

  - jinja2=3.0.3=pyhd8ed1ab_0

  - krb5=1.17.2=h926e7f8_0

  - ld_impl_linux-64=2.36.1=hea4e1c9_2

  - libblas=3.9.0=12_linux64_openblas

  - libcblas=3.9.0=12_linux64_openblas

  - libcurl=7.71.1=hcdd3856_3

  - libdeflate=1.0=h14c3975_1

  - libedit=3.1.20191231=h46ee950_2

  - libffi=3.3=h58526e2_2

  - libgcc-ng=11.2.0=h1d223b6_11

  - libgfortran-ng=11.2.0=h69a702a_11

  - libgfortran5=11.2.0=h5c6108e_11

  - libgomp=11.2.0=h1d223b6_11

  - liblapack=3.9.0=12_linux64_openblas

  - libopenblas=0.3.18=pthreads_h8fe5266_0

  - libssh2=1.10.0=ha56f1ee_2

  - libstdcxx-ng=11.2.0=he4da1e4_11

  - libzlib=1.2.11=h36c2ea0_1013

  - markupsafe=2.0.1=py36h8f6f2f9_0

  - ncurses=6.1=hf484d3e_1002

  - numpy=1.19.5=py36hfc0c790_2

  - openssl=1.1.1l=h7f98852_0

  - perl=5.32.1=1_h7f98852_perl5

  - pigz=2.6=h27826a3_0

  - pip=21.3.1=pyhd8ed1ab_0

  - pysam=0.15.3=py36hda2845c_1

  - python=3.6.10=h0371630_0

  - python_abi=3.6=2_cp36m

  - pyyaml=5.4.1=py36h8f6f2f9_1

  - readline=7.0=hf8c457e_1001

  - samtools=1.9=h8571acd_11

  - setuptools=49.6.0=py36h5fab9bb_3

  - sqlite=3.31.1=h7b6447c_0

  - star=2.7.9a=h9ee0642_0

  - tk=8.6.11=h27826a3_1

  - wgsim=1.0=h5bf99c6_4

  - wheel=0.37.0=pyhd8ed1ab_1

  - xz=5.2.5=h516909a_1

  - yaml=0.2.5=h516909a_0

  - zlib=1.2.11=h36c2ea0_1013

prefix: /gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/env_crossmapper

**Comment by ahmedihafez** [comment]
HI @GrantHov,
Probably it is a conflict caused by ```conda``` channels, can you let me know the output of the following command,
```
conda info
conda config --show channels
conda config --show default_channels
```

Thanks

**Comment by GrantHov** [comment]
Hi Ahmed, please find them below, thanks!
```

$ conda info



     active environment : env_crossmapper

    active env location : /gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs/env_crossmapper

            shell level : 2

       user config file : /home/vdelolmo/.condarc

 populated config files : /home/vdelolmo/.condarc

          conda version : 4.11.0

    conda-build version : 3.20.5

         python version : 3.8.5.final.0

       virtual packages : __cuda=11.2=0

                          __linux=4.12.14=0

                          __glibc=2.26=0

                          __unix=0=0

                          __archspec=1=x86_64

       base environment : /gpfs/projects/bsc40/current/vdelolmo/anaconda3  (writable)

      conda av data dir : /gpfs/projects/bsc40/current/vdelolmo/anaconda3/etc/conda

  conda av metadata url : None

           channel URLs : https://conda.anaconda.org/bioconda/linux-64

                          https://conda.anaconda.org/bioconda/noarch

                          https://conda.anaconda.org/conda-forge/linux-64

                          https://conda.anaconda.org/conda-forge/noarch

                          https://repo.anaconda.com/pkgs/main/linux-64

                          https://repo.anaconda.com/pkgs/main/noarch

                          https://repo.anaconda.com/pkgs/r/linux-64

                          https://repo.anaconda.com/pkgs/r/noarch

                          https://conda.anaconda.org/r/linux-64

                          https://conda.anaconda.org/r/noarch

                          https://conda.anaconda.org/anaconda/linux-64

                          https://conda.anaconda.org/anaconda/noarch

          package cache : /gpfs/projects/bsc40/current/vdelolmo/anaconda3/pkgs

                          /home/vdelolmo/.conda/pkgs

       envs directories : /gpfs/projects/bsc40/current/vdelolmo/anaconda3/envs

                          /home/vdelolmo/.conda/envs

               platform : linux-64

             user-agent : conda/4.11.0 requests/2.24.0 CPython/3.8.5 Linux/4.12.14-lp150.12.82-default opensuse-leap/15.0 glibc/2.26

                UID:GID : 1001:100

             netrc file : None

           offline mode : False




conda config --show channels

channels:

  - bioconda

  - conda-forge

  - defaults

  - r

  - anaconda





conda config --show default_channels

default_channels:

  - https://repo.anaconda.com/pkgs/main

  - https://repo.anaconda.com/pkgs/r

```

**Comment by ahmedihafez** [comment]
Ok Lets try the following,
First i would try to edit the order of the channels and see if that would fix it,
The channels are listed in the following file ```.condarc``` located on you home directory. Just open it with you favorite editor and put defaults at the top of the list.
And try to install the package again in a new env.
If that does not fix the env, then try to remove all other channels and keep only defaults. and try again and let me know how it goes.

**Comment by GrantHov** [comment]
Changing the default channel to the top made made it work! Thanks Ahmed!
I will add this case to troubleshooting!
